version: '3'
services:
  server:
    build: .
    ports:
    - 8000:8000
    depends_on:
    - database

  database:
    image: postgres:latest
    volumes: 
    - postgres:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=1234
    ports:
    - 5432:5432
volumes:
  postgres: